version: '2'

services:
  ODIdatabase:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    container_name: ODIdatabase
    volumes:
      - odiDBData:/ORCL
    ports:
      - 1521:1521
    environment:
      ORACLE_PDB: ORCLPDB1
    networks: 
      default:
        aliases:
        - docker.avanttic.com

  ODIagent:
    image: docker.avanttic.com/odiagent:12.2.1.3
    container_name: ODIagent
    ports:
      - 20910:20910
      - 5901:5901
    environment:
      RCUPREFIX: CON
      DB_HOST: docker.avanttic.com
      DB_PORT: 1521
      DB_SERVICE: ORCLPDB1
      DB_PASSWORD: Oradoc_db1
      DB_SCHEMA_PASSWORD: Welcome1
      SUPERVISOR_PASSWORD: Welcome1
      WORK_REPO_NAME: WORKREP
      WORK_REPO_PASSWORD: Welcome1
      HOST_NAME: docker.avanttic.com
    networks: 
      default:
        aliases:
        - docker.avanttic.com
